bits 64

; Handler and stub are defined in C, so i will just declare them here
global isr_stub_table
extern idt_handler_c

section .text

; ------------------------------------------------------------------------------
; Macro: ISR_NOERR
; Used for interrupts that DO NOT push an error code onto the stack
; ------------------------------------------------------------------------------
%macro ISR_NOERR 1
global isr%1
isr%1:
    push qword 0    ; Push dummy error code to keep stack alignment consistent
    push qword %1   ; Push the interrupt vector number
    jmp isr_common  ; Jump to the shared handler code
%endmacro

; ------------------------------------------------------------------------------
; Macro: ISR_ERR
; Used for CPU exceptions that automatically push an error code onto the stack
; ------------------------------------------------------------------------------
%macro ISR_ERR 1
global isr%1
isr%1:
    push qword %1   ; Push the interrupt vector number
    jmp isr_common  ; Jump to the shared handler code
%endmacro

; ==============================================================================
; CPU EXCEPTIONS (0 - 31)
; ==============================================================================
ISR_NOERR 0  ; Divide-by-Zero
ISR_NOERR 1  ; Debug
ISR_NOERR 2  ; Non-Maskable Interrupt
ISR_NOERR 3  ; Breakpoint
ISR_NOERR 4  ; Overflow
ISR_NOERR 5  ; Bound Range Exceeded
ISR_NOERR 6  ; Invalid Opcode
ISR_NOERR 7  ; Device Not Available

ISR_ERR   8  ; Double Fault (Pushes Error Code!)
ISR_NOERR 9  ; Coprocessor Segment Overrun
ISR_ERR   10 ; Invalid TSS (Pushes Error Code!)
ISR_ERR   11 ; Segment Not Present (Pushes Error Code!)
ISR_ERR   12 ; Stack-Segment Fault (Pushes Error Code!)
ISR_ERR   13 ; General Protection Fault (Pushes Error Code!)
ISR_ERR   14 ; Page Fault (Pushes Error Code!)
ISR_NOERR 15 ; Reserved

ISR_NOERR 16 ; x87 Floating-Point Exception
ISR_ERR   17 ; Alignment Check (Pushes Error Code!)
ISR_NOERR 18 ; Machine Check
ISR_NOERR 19 ; SIMD Floating-Point Exception
ISR_NOERR 20 ; Virtualization Exception
ISR_ERR   21 ; Control Protection Exception (Pushes Error Code!)
ISR_NOERR 22 ; Reserved
ISR_NOERR 23 ; Reserved

ISR_NOERR 24 ; Reserved
ISR_NOERR 25 ; Reserved
ISR_NOERR 26 ; Reserved
ISR_NOERR 27 ; Reserved
ISR_NOERR 28 ; Hypervisor Injection Exception
ISR_ERR   29 ; VMM Communication Exception (Pushes Error Code!)
ISR_ERR   30 ; Security Exception (Pushes Error Code!)
ISR_NOERR 31 ; Reserved

; ==============================================================================
; HARDWARE AND SOFTWARE INTERRUPTS (32 - 255)
; ==============================================================================
; None of these custom vectors push an error code, so i use ISR_NOERR
; They are not CPU exceptions, rather hardware and software interrupts
; ------------------------------------------------------------------------------
%assign i 32
%rep 224
    ISR_NOERR i
%assign i i+1
%endrep

; ==============================================================================
; SHARED ISR COMMON CODE
; ==============================================================================
; This block saves the entire CPU state, passes a pointer to the stack frame
; into the C dispatcher, and restores everything once the handler returns
; ------------------------------------------------------------------------------
isr_common:
    ; Push general purpose registers onto the stack
    push r15
    push r14
    push r13
    push r12
    push r11
    push r10
    push r9
    push r8
    push rbp
    push rdi
    push rsi
    push rdx
    push rcx
    push rbx
    push rax

    ; Pass a pointer to the stack frame as the first argument (RDI)
    mov rdi, rsp

    ; Call the C central dispatcher
    call idt_handler_c

    ; Pop everything back
    pop rax
    pop rbx
    pop rcx
    pop rdx
    pop rsi
    pop rdi
    pop rbp
    pop r8
    pop r9
    pop r10
    pop r11
    pop r12
    pop r13
    pop r14
    pop r15

    ; Clean up the interrupt number and the error code i pushed earlier
    add rsp, 16

    ; Return from interrupt
    iretq

; ==============================================================================
; AUTOGENERATED POINTER TABLE
; ==============================================================================
section .data
align 8
isr_stub_table:
%assign i 0
%rep 256
    dq isr%+i
%assign i i+1
%endrep
